steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]
    dir: 'cms'

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build:libs' ]
    dir: 'cms'

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build' ]
    dir: 'cms'

