name: Deploy cms demo

on: 
  push:
    branches:
      - 'deploy/**'

jobs:
  cms-deploy:
    name: Deploy Angular To Github Page
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cms

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm 
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: |
          npm run build:libs
          npm run build -- --prod
          npm run deploy -- --no-silent --name="danghung1202" --email=danghung1202@gmail.com

  api-deploy:
    name: Deploy Node Api To Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cms-api